# 기본 사이트 설정
title: ChocoBreeze Blog
description: Welcome to my GitHub Pages blog
url: "https://chocobreeze.github.io/"

# 테마 설정
remote_theme: mmistakes/minimal-mistakes

# 사이트의 로고 이미지 및 기본 옵션 설정
logo: "/assets/images/logo.png"

# 네비게이션 메뉴 설정 (필요시 사용)
navigation:
  - title: "Home"
    url: "/"
  - title: "Categories"
    url: "/categories/"
  - title: "About"
    url: "/about/"

# 저자 설정
author:
  name: ChocoBreeze
  email: your-email@example.com

# 소셜 아이콘 설정
social:
  twitter: your_twitter_handle
  github: ChocoBreeze
