title: ChocoBreeze Blog
description: Welcome to my GitHub Pages blog
url: "https://chocobreeze.github.io/"  # 본인의 GitHub Pages URL로 수정
remote_theme: lorepirri/cayman-blog

author: ChocoBreeze
show_downloads: true  # GitHub 저장소 다운로드 버튼을 보여줄지 여부

navigation:
  - title: "Home"
    url: "/"
  - title: "Categories"
    url: "/categories/"
