title: Welcome to ChocoBreeze Blog # 사이트 제목
description: 개발 관련 공부 내용 기록 # 사이트 설명
baseurl: "" # 사이트의 서브 디렉토리 경로입니다. GitHub Pages의 경우 보통 "/repository-name" 형식으로 설정합니다.
url: "https://chocobreeze.github.io" # 사이트의 기본 도메인 = 배포될 도메인 주소

# Author
author-name: ChocoBreeze
author-image: "Okeydokey/pic%20(62).jpg"
author-job: Developer
author-email: # Add your email for contant form.
about-author: "- 너무 늦게 자지 않기<br/>- 끼니 거르지 않기<br/>- 이유 생각하기"

# Social settings
social-twitter: 
social-facebook:
social-github: ChocoBreeze
social-pinterest: 
social-instagram: breezechoco
social-youtube: 
social-vk:   
social-linkedin:
social-naver: chocobreeze

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
# MailChimp는 이메일 뉴스레터 구독을 관리하는 서비스입니다.

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1 
# Google Analytics는 웹사이트 방문자 트래픽을 분석하는 도구입니다.

# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown
# Disqus는 웹사이트에 댓글 기능을 추가하는 외부 서비스입니다.
# 일단은 하지 말자.

# 추가
highlighter: rouge

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    inline_theme: github

permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layout: category
  permalinks:
    category: /category/:name/

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages
  - search.json

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
